export const initialData = [
  {
    icon: "FaFilePdf",
    name: "Tech requirements.pdf",
    size: "200 KB",
    type: "Legal",
    ai: true,
    dashboard: true,
    stage: "Full",
  },
  {
    icon: "FaFilePdf",
    name: "Dashboard screenshot.jpg",
    size: "720 KB",
    type: "Vendors & Assets",
    ai: true,
    dashboard: true,
    stage: "Onboarding",
  },
  {
    icon: "IoDocumentTextSharp",
    name: "Dashboard prototype recording.mp4",
    size: "16 MB",
    type: "Technology",
    ai: false,
    dashboard: true,
    stage: "Franchisee",
  },
  {
    icon: "IoDocumentTextSharp",
    name: "Financial Overview",
    size: "4.2 MB",
    type: "Financial",
    ai: true,
    dashboard: true,
    stage: "Prospect",
  },
  {
    icon: "FaFilePdf",
    name: "Dashboard interaction.aep",
    size: "12 MB",
    type: "Legal",
    ai: true,
    dashboard: true,
    stage: "Onboarding",
  },
  {
    icon: "IoDocumentTextSharp",
    name: "UX Design Guidelines.docx",
    size: "400 KB",
    type: "Legal",
    ai: true,
    dashboard: false,
    stage: "Onboarding",
  },
  {
    icon: "FaFilePdf",
    name: "Briefing call recording.mp3",
    size: "18.6 MB",
    type: "Financial",
    ai: false,
    dashboard: false,
    stage: "Prospect",
  },
];
